log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

certificatesResolvers:
  selfsigned:
    acme:
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: "developer@vibetoons.com"
      storage: "/var/traefik/certs/letsencrypt/acme.json"
      keyType: "RSA4096"
      tlsChallenge: {}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/ssl/certs/traefik-selfsigned.crt"
        keyFile: "/etc/ssl/private/traefik-selfsigned.key"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
